// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title: string;
  cover: File;

  constructor(private http: HttpClient) {}

  onTitleChanged(event: any) {
    this.title = event.target.value;
  }

  onImageChanged(event: any) {
    this.cover = event.target.files[0];
  }

  newBook() {
    const uploadData = new FormData();
    uploadData.append('title', this.title);
    uploadData.append('cover', this.cover, this.cover.name);
    this.http.post('http://127.0.0.1:8000/books/', uploadData).subscribe(
      data => console.log(data),
      error => console.log(error)
    );
  }
}

<h3>Upload images with Angular</h3>

<label>
  Title:
  <input type="text" (change)="onTitleChanged($event)" />
</label>
<br/>
<label>
  Cover:
  <input type="file" (change)="onImageChanged($event)" />
</label>
<br/>
<button (click)="newBook()">New Book</button>

// react/src/App.js
import React, { useState } from 'react';
import './App.css';

function App() {

  const [ title, setTitle ] = useState("");
  const [ cover, setCever ] = useState();

  const newBook = () => {
    const uploadData = new FormData();
    uploadData.append('title', title);
    uploadData.append('cover', cover, cover.name);
    
    fetch('http://127.0.0.1:8000/books/', {
      method: 'POST',
      body: uploadData
    })
    .then( res => console.log(res))
    .catch(error => console.log(error))
  }

  return (
    <div className="App">
      <h3>Upload images with React</h3>
      <label>
        Title
        <input type="text" value={title} onChange={(evt) => setTitle(evt.target.value)}/>
      </label>
      <br/>
      <label>
        Cover
        <input type="file" onChange={(evt) => setCever(evt.target.files[0])}/>
      </label>
      <br/>
      <button onClick={() => newBook()}>New Book</button>
    </div>
  );
}

export default App;
